//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSystemApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourseGradeViewModel
    {
        public int Id { get; set; }
        public int StdRegId { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public int CourseId { get; set; }
        public int GradeId { get; set; }
        public string GradeName { get; set; }
    }
}
